export const PREDICTION_MODELS = {
  LINEAR_REGRESSION: "linear_regression",
  RANDOM_FOREST: "random_forest",
  XGBOOST: "xgboost",
  PROPHET: "prophet"
};

export const PREDICTION_MODEL_VALUES = [
  PREDICTION_MODELS.LINEAR_REGRESSION,
  PREDICTION_MODELS.RANDOM_FOREST,
  PREDICTION_MODELS.XGBOOST,
  PREDICTION_MODELS.PROPHET
];